- src/main/java/se/sundsvall/emailreader/Application.java
- src/main/java/se/sundsvall/emailreader/configuration/ShedLockConfiguration.java
- src/main/java/se/sundsvall/emailreader/service/EmailScheduler.java
- src/test/java/se/sundsvall/emailreader/ShedlockAnnotationsTest.java
- Added missing parts for shedlock to work
- Added shedlock to scheduled task that was missing it
- Extended with tests for verifying that all scheduled tasks has the correct annotations and that shedlock is enabled and working
> UF-6891: Added missing parts for shedlock to work

- src/main/java/se/sundsvall/emailreader/service/EmailScheduler.java
> fix invalid mail loop

- src/main/java/se/sundsvall/emailreader/integration/messaging/MessagingConfiguration.java
> UF-10321: Fix email-report bug

- src/main/resources/application.yml
> removed redundant config

- src/main/java/se/sundsvall/emailreader/integration/messaging/MessagingConfiguration.java
- src/main/resources/application.yml
> Properties fix

- src/main/java/se/sundsvall/emailreader/integration/ews/EWSIntegration.java
- src/main/java/se/sundsvall/emailreader/integration/messaging/MessagingConfiguration.java
- src/test/java/se/sundsvall/emailreader/integration/ews/EWSIntegrationTest.java
> UF-10974: Create folder instead of throwing exception

- src/main/java/se/sundsvall/emailreader/integration/messaging/MessagingClient.java
> UF-11345: Added circuit breaker

- src/main/java/se/sundsvall/emailreader/service/EmailService.java
> UF-11575: Fix autosubmitted-check bug

- README.md
- src/integration-test/resources/openapi.yml
- src/main/java/se/sundsvall/emailreader/api/CredentialsResource.java
- src/main/java/se/sundsvall/emailreader/api/EmailResource.java
> UF-11149: Add readme

- src/main/java/se/sundsvall/emailreader/service/EmailScheduler.java
- src/test/java/se/sundsvall/emailreader/service/EmailSchedulerTest.java
> UF-14348: Add more logs when exception ocurrs

- src/main/java/se/sundsvall/emailreader/integration/ews/EWSMapper.java
- src/test/java/se/sundsvall/emailreader/integration/ews/EWSMapperTest.java
> UF-14358: Fix faulty entity mappar

- src/main/java/se/sundsvall/emailreader/integration/ews/EWSIntegration.java
- src/main/java/se/sundsvall/emailreader/service/EmailScheduler.java
- src/main/java/se/sundsvall/emailreader/service/EmailService.java
- src/test/java/se/sundsvall/emailreader/integration/ews/EWSIntegrationTest.java
- src/test/java/se/sundsvall/emailreader/service/EmailSchedulerTest.java
- src/test/java/se/sundsvall/emailreader/service/EmailServiceTest.java
> UF-14508: Exceptions should trigger healthcheck

- src/generated/messaging.yml
> UF-14626: Update to messaging 6.1

- pom.xml
- src/integration-test/resources/openapi.yml
- src/main/java/se/sundsvall/emailreader/api/GraphCredentialsResource.java
- src/main/java/se/sundsvall/emailreader/api/model/GraphCredentials.java
- src/main/java/se/sundsvall/emailreader/service/GraphCredentialsService.java
- src/test/java/se/sundsvall/emailreader/api/GraphCredentialsResourceTest.java
- src/test/java/se/sundsvall/emailreader/api/model/GraphCredentialsTest.java
- src/test/java/se/sundsvall/emailreader/service/GraphCredentialsServiceTest.java
> UF-15044: Add api resource for graph credentials

- pom.xml
- src/main/java/se/sundsvall/emailreader/integration/graph/GraphClient.java
- src/main/java/se/sundsvall/emailreader/integration/graph/GraphIntegration.java
- src/main/java/se/sundsvall/emailreader/integration/graph/GraphMapper.java
- src/test/java/se/sundsvall/emailreader/integration/graph/GraphClientTest.java
- src/test/java/se/sundsvall/emailreader/integration/graph/GraphIntegrationTest.java
- src/test/java/se/sundsvall/emailreader/integration/graph/GraphMapperTest.java
> UF-14715: Add graph integration

- src/integration-test/resources/openapi.yml
- src/main/java/se/sundsvall/emailreader/api/GraphCredentialsResource.java
- src/main/java/se/sundsvall/emailreader/service/GraphCredentialsService.java
- src/main/java/se/sundsvall/emailreader/service/mapper/GraphCredentialsMapper.java
- src/test/java/se/sundsvall/emailreader/service/GraphCredentialsServiceTest.java
- src/test/java/se/sundsvall/emailreader/service/mapper/GraphCredentialsMapperTest.java
> UF-15062: Add servicelayer logic for graphCredentials

- src/integration-test/resources/openapi.yml
- src/main/java/se/sundsvall/emailreader/api/GraphCredentialsResource.java
- src/main/java/se/sundsvall/emailreader/integration/ews/EWSIntegration.java
- src/main/java/se/sundsvall/emailreader/integration/graph/GraphClient.java
- src/main/java/se/sundsvall/emailreader/integration/graph/GraphIntegration.java
- src/main/java/se/sundsvall/emailreader/integration/graph/GraphMapper.java
- src/main/java/se/sundsvall/emailreader/service/EmailService.java
- src/main/java/se/sundsvall/emailreader/service/scheduler/EwsScheduler.java
- src/main/java/se/sundsvall/emailreader/service/scheduler/GraphScheduler.java
- src/main/resources/application.yml
- src/test/java/se/sundsvall/emailreader/integration/graph/GraphClientTest.java
- src/test/java/se/sundsvall/emailreader/integration/graph/GraphIntegrationTest.java
- src/test/java/se/sundsvall/emailreader/integration/graph/GraphMapperTest.java
- src/test/java/se/sundsvall/emailreader/service/scheduler/EwsSchedulerTest.java
- src/test/java/se/sundsvall/emailreader/service/scheduler/GraphSchedulerTest.java
> UF-15046: Add scheduledJob for fetching from graph

- src/integration-test/java/se/sundsvall/emailreader/apptest/GraphCredentialsIT.java
- src/integration-test/resources/GraphCredentialsIT/__files/test1_fetchCredentials/response.json
- src/integration-test/resources/GraphCredentialsIT/__files/test2_createCredentials/request.json
- src/integration-test/resources/GraphCredentialsIT/__files/test2_createCredentials/response.json
- src/integration-test/resources/GraphCredentialsIT/__files/test3_updateCredentials/request.json
- src/integration-test/resources/GraphCredentialsIT/__files/test3_updateCredentials/response.json
- src/integration-test/resources/openapi.yml
- src/integration-test/resources/sql/init-db.sql
- src/integration-test/resources/sql/truncate.sql
- src/main/java/se/sundsvall/emailreader/api/GraphCredentialsResource.java
- src/main/java/se/sundsvall/emailreader/service/GraphCredentialsService.java
- src/test/java/se/sundsvall/emailreader/api/GraphCredentialsResourceTest.java
- src/test/java/se/sundsvall/emailreader/service/GraphCredentialsServiceTest.java
> UF-15063: Add IT test for graph credentials

- src/main/java/se/sundsvall/emailreader/integration/graph/GraphClient.java
- src/main/resources/application-it.yml
- src/main/resources/application-junit.yml
- src/test/java/se/sundsvall/emailreader/integration/graph/GraphClientTest.java
> UF-15110: Create folder if not exists

- src/main/java/se/sundsvall/emailreader/integration/ews/EWSIntegration.java
- src/test/java/se/sundsvall/emailreader/integration/ews/EWSIntegrationTest.java
> UF-15725: Fix Email to SMS bug.

- src/integration-test/java/se/sundsvall/emailreader/openapi/OpenApiSpecificationIT.java
- src/integration-test/resources/GraphCredentialsIT/__files/test1_fetchCredentials/response.json
- src/integration-test/resources/GraphCredentialsIT/__files/test2_createCredentials/request.json
- src/integration-test/resources/GraphCredentialsIT/__files/test2_createCredentials/response.json
- src/integration-test/resources/GraphCredentialsIT/__files/test3_updateCredentials/request.json
- src/integration-test/resources/GraphCredentialsIT/__files/test3_updateCredentials/response.json
- src/integration-test/resources/openapi.yml
- src/integration-test/resources/sql/init-db.sql
- src/main/java/se/sundsvall/emailreader/api/model/Credentials.java
- src/main/java/se/sundsvall/emailreader/api/model/GraphCredentials.java
- src/main/java/se/sundsvall/emailreader/integration/db/CredentialsRepository.java
- src/main/java/se/sundsvall/emailreader/integration/db/entity/CredentialsEntity.java
- src/main/java/se/sundsvall/emailreader/integration/db/entity/GraphCredentialsEntity.java
- src/main/java/se/sundsvall/emailreader/service/EmailService.java
- src/main/java/se/sundsvall/emailreader/service/mapper/CredentialsMapper.java
- src/main/java/se/sundsvall/emailreader/service/mapper/GraphCredentialsMapper.java
- src/main/java/se/sundsvall/emailreader/service/scheduler/EwsScheduler.java
- src/main/resources/db/migration/V1_10__add_enable_column_credentials.sql
- src/test/java/se/sundsvall/emailreader/api/model/CredentialsTest.java
- src/test/java/se/sundsvall/emailreader/api/model/GraphCredentialsTest.java
- src/test/java/se/sundsvall/emailreader/integration/db/entity/GraphCredentialsEntityTest.java
- src/test/java/se/sundsvall/emailreader/service/EmailServiceTest.java
- src/test/java/se/sundsvall/emailreader/service/scheduler/EwsSchedulerTest.java
- src/test/resources/db/scripts/schema.sql
- src/test/resources/db/scripts/testdata-junit.sql
> UF-10915: make it possible to toggle mailboxes on and off

- src/main/java/se/sundsvall/emailreader/service/EmailService.java
- src/test/java/se/sundsvall/emailreader/service/EmailServiceTest.java
> UF-16533: filter out noreply senders

- .gitignore
- src/main/java/se/sundsvall/emailreader/integration/ews/EWSIntegration.java
- src/main/java/se/sundsvall/emailreader/integration/ews/EWSMapper.java
- src/main/java/se/sundsvall/emailreader/service/EmailService.java
- src/main/java/se/sundsvall/emailreader/service/scheduler/EwsScheduler.java
- src/test/java/se/sundsvall/emailreader/integration/ews/EWSIntegrationTest.java
- src/test/java/se/sundsvall/emailreader/service/EmailServiceTest.java
- src/test/java/se/sundsvall/emailreader/service/scheduler/EwsSchedulerTest.java
> UF-16662: Optimize ews-fetching a bit and prevent too large mails to be read

- src/main/java/se/sundsvall/emailreader/service/EmailService.java
- src/test/java/se/sundsvall/emailreader/service/EmailServiceTest.java
> UF-17090: move autoreply emails instead of deleting them

- src/main/java/se/sundsvall/emailreader/service/EmailService.java
- src/main/java/se/sundsvall/emailreader/service/scheduler/EwsScheduler.java
- src/main/java/se/sundsvall/emailreader/service/scheduler/GraphScheduler.java
> UF-17089: Improve and extend logging

- src/main/java/se/sundsvall/emailreader/integration/ews/EWSMapper.java
- src/test/java/se/sundsvall/emailreader/integration/ews/EWSMapperTest.java
> UF-17091: remove whitespace characters from headers
